Arbitro:
  type: entity
  table: Arbitro
  fields:
    dni:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nombre:
      type: string
      length: 45
      fixed: false
      nullable: true
    apellido:
      type: string
      length: 45
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
