<?php

namespace Area4\ContableBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LineadeDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineadeDocumentoRepository extends EntityRepository
{
}