<?php

namespace Area4\ContableBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EgresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgresoRepository extends EntityRepository
{
	/**
	 * Genera la busqueda de todos los egresos entre las dos fecha
	 * que se entregan por parametro
	 *
	 * @author ezekiel
	 **/
	public function reporte($fecha_inicio, $fecha_fin)
	{
		//die(var_dump($fecha_inicio));
		$query = $this->createQueryBuilder('e')
                ->where('e.fecha >= \''.$fecha_inicio->format('Y-m-d').'\'')
                ->andWhere('e.fecha <= \''.$fecha_fin->format('Y-m-d').'\'')
                ->orderBy('e.fecha', 'ASC')
                ->getQuery();
        return $query->getResult();
	}
}