<?php

namespace Area4\CampeonatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
    // SELECT nombre FROM `Camp_Categoria` WHERE `fecha_ini`< '1995-01-01' AND `fecha_fin` > '1995-01-01'
    /**
     *
     * @param date $fecha
     */
    public function catApropiada($fecha){
        $edad = \date('Y') - $fecha;
        return $this->createQueryBuilder('c')
                ->where('c.edadIni <= \''.$edad.'\'')
                ->andWhere('c.edadFin >= \''.$edad.'\'')
                ->orderBy('c.edadFin', 'DESC')
                ->getQuery()
                ->getResult()
            ;
    }
}