<?php

namespace Area4\CampeonatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
	static private $bloques = array(
	 	'SB'=> 'Sin Bloque',
    	'A' => 'A', 
    	'B' => 'B', 
    	'C' => 'C', 
    	'D' => 'D'
    );

    static private $colores = array(
        'SC' => 'Sin Color',
        'AZUL' => 'AZUL',
        'ROJO' => 'ROJO',
        'AMARILLO' => 'AMARILLO',
        'VERDE' => 'VERDE',
        'BLANCO' => 'BLANCO',
        'NEGRO' => 'NEGRO',
        'CELESTE' => 'CELESTE',
        'GRIS' => 'GRIS',
    );

    /**
	 * Devuleve los bloques
	 * @return array c/ todos los bloques disponibles
	 */
    static function getBloques()
    {
    	return self::$bloques;
    }
    /**
     * Devuleve los colores
     * @return array c/ todos los colores disponibles
     */
    static function getColores()
    {
        return self::$colores;
    }

    /**
     * Busca los equipos de un determinado campeonato
     *
     * @param $id : id del Campeonato
     * @return Equipo
     * @author ezekiel
     **/
    public function findByCampeonato($id)
    {
        $query = $this->createQueryBuilder('e')
                    ->join('e.campeonato','c')
                    ->where('c.id = '.$id)
                    ->setMaxResults('2')
                    ->getQuery();
        return $query->getResult();
    }

    /**
     * Busca los equipos que no juegan en dicho campeonato
     *
     * @return Array Equipos
     * @author ezekiel
     * @param $idCampeoanto : id del campeonato
     **/
    public function findNotPlayInCampeonato($idCampeonato)
    {
        $query = $this->createQueryBuilder('e')
                    ->join('e.campeonato','c')
                    ->where('c.id <> '.$idCampeonato)
                    ;
        return $query;
    }
}