<?php

namespace Area4\CampeonatoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
/**
 * novedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class novedadRepository extends EntityRepository
{
	
}