<?php

namespace Area4\CampeonatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * partidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidoRepository extends EntityRepository
{

	private static $estados = array(
		'PJU' => 'Por jugarse',
		'JUG' => 'Jugandose',
		'SUS' => 'Suspendido',
		'FIN' => 'Finalizado',
	);

	public static function getEstados()
	{
		return self::$estados;
	}

    public function partidoOrderByFecha()
    {
        return $this->createQueryBuilder('p')
                ->orderBy('p.fecha','ASC')
                ->getQuery()
                ->getResult()
            ;
    }

}